[package]
name = "hash"
version = "0.1.0"
edition = "2018"
authors=["rune"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust-crypto="0.2"
